services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./data:/app/data
      - ./custom_assets:/app/custom_assets
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/compass.crt:/etc/nginx/ssl/compass.crt:ro
      - ./docker/nginx/compass.key:/etc/nginx/ssl/compass.key:ro
    depends_on:
      - web

